###
#   Values for deployment using GitLab container registry
###

# Global
global:
  ingress:
    host: 
 
# Individual service overrides
feature-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 3000
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/feature-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab

mapping-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 3000
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/mapping-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab
  
namedresource-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 3000
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/namedresource-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab

tiling-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 3000
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/tiling-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab

repository-service-gold:
  requestCPU: "100m"
  limitCPU: "4"
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/repository-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab
  
repository-service:
  requestCPU: "500m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 3000
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/repository-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab

spatialmanager-service:
  requestCPU: "100m"
  limitCPU: "4"
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework/spatialmanager-service
    tag: 1.0-SNAPSHOT
    secrets: regcred-gitlab

# END

